clusterName: 'journey.dev.local'
kubernetesVersion: 1.14.0
kopsStateBucket: 'br-com-k8sguru-kops-state-prod'
kubeConfig: '$HOME/.kubernetes-cluster/kube/config'
master:
  machineType: t3.medium
  maxSize: 1
  minSize: 1
  instances:
    - m5.large
    - t3.medium
    - c4.large
  onDemandAboveBase: 0
  onDemandBase: 0
  spotInstancePools: 3
  azs:
    - 'us-east-1a'
nodes:
  machineType: t3.large
  maxSize: 3
  minSize: 3
  instances:
    - m5.large
    - t3.medium
    - c4.large
  onDemandAboveBase: 0
  onDemandBase: 0
  spotInstancePools: 3
  azs:
    - 'us-east-1a'
    - 'us-east-1b'
    - 'us-east-1c'
