env:
  name: 'prod'
  region: 'us-east-1'
  bucket_terragrunt_state: 'br-com-k8sguru-terragrunt-state-prod'
  dynamodb_table: 'br-com-k8sprodap-terragrunt-locks'
zone:
  name: 'k8sguru.info'
  id: 'ZXX5YL5YERQ7H'
  cert: 'arn:aws:acm:us-east-1:105030913021:certificate/9822346b-c9a2-439b-88d6-31853b620b73'
vpc:
  cidr: '10.0.0.0/16'
  azs:
    - 'us-east-1a'
    - 'us-east-1b'
    - 'us-east-1c'
  private_subnets:
    - '10.0.1.0/24'
    - '10.0.2.0/24'
    - '10.0.3.0/24'
  public_subnets:
    - '10.0.101.0/24'
    - '10.0.102.0/24'
    - '10.0.103.0/24'
prereqs:
  ingressIps:
    - '10.0.0.100/32'
    - '10.0.0.101/32'
tiller:
  helmHome: '$HOME/.helm'
